hw2
Yushkov88/nodejs-rest-api pull request #1
Opened 2023-01-03 08:50 UTC by Yushkov88

Добрый день!проверьте пожалуйста

2023-01-03 09:42 UTC, KhYulian commented on controllers/contacts/getContactById.js
> +  res.json({ status: "success", code: 200, data: contact });
status: "success", code: 200, - непотрібні. доля вказування статусу використовуйте .status(statusCode).json(contact)

2023-01-03 09:42 UTC, KhYulian commented on controllers/contacts/updateContact.js
> +module.exports = updateContact;
Контролдлерів в даному випадку небагато та вони прості, тому краще їх обєднати у contactsControllers.js

2023-01-03 09:43 UTC, KhYulian commented on helpers/RequestError.js
> +};
використовуйте класи class RequestError extends Error {}

2023-01-03 09:43 UTC, KhYulian commented on helpers/ctrlWrapper.js
> +const ctrlWrapper = (ctrl) => {
controllerWrapper

2023-01-03 09:44 UTC, KhYulian commented on routes/api/contacts.js
> +router.get("/", ctrlWrapper(ctrl.contacts.listContacts));
зробіть деструктуризацію

2023-01-03 09:45 UTC, KhYulian commented on schemas/contacts.js
> +});
також має бути схема для оновлення контакту, де буде вказанор, що хоча б одне поле є обовязковим, а не усі -.min(1)

2023-01-03 09:45 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-03 09:46 UTC, KhYulian commented
Також відповідайте на коменти по мірі виправлення

2023-01-05 08:14 UTC, Yushkov88 commented on controllers/contacts/getContactById.js
> +  res.json({ status: "success", code: 200, data: contact });
пофиксил

2023-01-05 08:14 UTC, Yushkov88 commented on helpers/RequestError.js
> +};
исправил на классы

2023-01-05 08:17 UTC, Yushkov88 commented on helpers/ctrlWrapper.js
> +const ctrlWrapper = (ctrl) => {
исправлено

2023-01-05 08:23 UTC, Yushkov88 commented on schemas/contacts.js
> +});
изменил

2023-01-05 10:57 UTC, Yushkov88 commented on controllers/contacts/updateContact.js
> +module.exports = updateContact;
перенес в api/contacts

2023-01-05 10:57 UTC, Yushkov88 commented on routes/api/contacts.js
> +router.get("/", ctrlWrapper(ctrl.contacts.listContacts));
done

2023-01-05 13:03 UTC, KhYulian approved these changes
:ok_hand:

2023-01-05 13:03 UTC, merged