hw3
Yushkov88/nodejs-rest-api pull request #2
Opened 2023-01-11 12:37 UTC by Yushkov88

Проверьте пожалуйста!

2023-01-11 13:12 UTC, KhYulian commented on controllers/contacts/getContactById.js
> +  res.json({ status: "success", code: 200, data: contact });
status: "success", code: 200б data  - непотрібні поля - видаляйте 
res.json(contact)

2023-01-11 13:13 UTC, KhYulian commented on controllers/contacts/updateStatusContact.js
> +  }
Виуористовуйте Joi

2023-01-11 13:14 UTC, KhYulian commented on helpers/RequestError.js
> +  return error;
Використовуйте класи

2023-01-11 13:14 UTC, KhYulian commented on helpers/RequestError.js
> -}
все ок було, використовуйте класи

2023-01-11 13:15 UTC, KhYulian commented on models/contacts.js
> +});
винесіть схеми Joi  в окремий файл

2023-01-11 13:15 UTC, KhYulian commented on routes/api/contacts.js
> +const ctrl = require("../../controllers");
Зробіть деструктуризацію

2023-01-11 13:16 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-12 06:12 UTC, Yushkov88 commented on controllers/contacts/getContactById.js
> +  res.json({ status: "success", code: 200, data: contact });
поправил!

2023-01-12 07:28 UTC, Yushkov88 commented on helpers/RequestError.js
> +  return error;
готово

2023-01-12 07:29 UTC, Yushkov88 commented on helpers/RequestError.js
> -}
+

2023-01-12 07:39 UTC, Yushkov88 commented on models/contacts.js
> +});
готово!

2023-01-12 07:46 UTC, Yushkov88 commented on controllers/contacts/updateStatusContact.js
> +  }
выполнил

2023-01-12 07:51 UTC, Yushkov88 commented on routes/api/contacts.js
> +const ctrl = require("../../controllers");
готово

2023-01-12 08:44 UTC, KhYulian approved these changes
Чудова робота!

2023-01-12 08:45 UTC, merged